spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost/blog?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
server:
  name: localhost
  port: 8081
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*Mapper.xml
jwt:
  header: JWTHeaderName
  secret: qweerasdfasdgahhasdfsadgfasghafhafasdgasdgqweerasdfasdgahhasdfsadgfasghafhafasdgasdgqweerasdfasdgahhasdfsadgfasghafhafasdgasdg
  expiration: 43200000