spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/blog?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: fenrana
#  mvc:
#    static-path-pattern: /image/**
#    resources:
#      static-locations: classpath:/images/
server:
  port: 8081
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
